### ISSUE TITLE
Camera stays active even after StopRecording/Dispose

### ISSUE THREAD

**Issue by Baklap4** [YannVasseur35/ReactorBlazorQRCodeScanner#12]
Currently looking through the code and i see that even when we call

```csharp
await this.qrCodeScannerJsInterop.StopRecording();
await this.qrCodeScannerJsInterop.DisposeAsync();
```
The scanner is still using our camera. (Shown in the android and iOS operating system).

I think not everything in javascript world is cleaned up properly and maybe in dotnet world the object-references/jsruntime.

**Comment by Baklap4** [comment]
Disregard this issue.

Problem was that we called `Init` twice. Once in the `OnInitialized` and second in a permission changed timer elapsed event where we checked if the user gave permission.

Fixed this by calling `StopRecording` and `DisposeAsync()` before calling the `Init` function within the elapsed timer event.

**Comment by YannVasseur35** [comment]
I don't have this behavior , tested on chrome (desktop) and chrome (android).

I'm using this 
@implements IAsyncDisposable

(...)

public async ValueTask DisposeAsync()
{
    // Async cleanup 
    if (_qrCodeScannerJsInterop != null)
    {
        await _qrCodeScannerJsInterop.StopRecording();
    }

    await Task.Yield();
}

**Comment by Baklap4** [comment]
Not even if you call Init twice? (that was happening essentially)

Might be a good thing to add in the library that Init can't be called twice, or that the 2nd time does nothing and uses the first instance
