### ISSUE TITLE
Styling the canvas

### ISSUE THREAD

**Issue by mattheys** [YannVasseur35/ReactorBlazorQRCodeScanner#3]
Hi, I want to add a width of 100% to the canvas object, I can do this by doing a global canvas#canvas { width: 100%; } but I would rather use something more targeted.  I can't seem to apply a style attribute or id to the <QRCodeScanner /> and CSS Isolation with ::deep seems to stop it from working all together.  Any suggestions?

**Comment by couscousbzh** [comment]
I realy suck in CSS, sorry...

**Comment by YannVasseur35** [comment]
I add on optional param "Width" on the component.
Give him width in pixel (Width="1080") or in % (Width="15%")
Default width depends on the video stream size.

**Comment by mattheys** [comment]
Thank you very much.
