### ISSUE TITLE
cannot read big QR

### ISSUE THREAD

**Issue by javirs85** [YannVasseur35/ReactorBlazorQRCodeScanner#4]
I created the QR on another app but the QR reader from android can read it so I assume the QR is correct. When I show the QR to the camera a red square get's drawn around the QR but the detection event does not fire.

This is the QR:
![image](https://user-images.githubusercontent.com/6223567/191255759-c0ad77a1-4841-414f-82c6-d1197dabb671.png)

Content should be a json formatted string, like: {name:javi,data:QWEASDAWQE,more and more}  with some long strings (where we encoded some plot's data)

PS: the setup works for simpler QR codes, so it is also not a configuration problem

**Comment by YannVasseur35** [comment]
this lib use jsQR.js javascript lib. 
I'm afraid if this one does not read your QR, the blazor lib won't neither.
