### ISSUE TITLE
Hide red lines of QR image shape

### ISSUE THREAD

**Issue by vladPanasiuk** [YannVasseur35/ReactorBlazorQRCodeScanner#5]
How can I hide red lines around QR code when scanning it? Is it possible?
![photo_2022-11-28_19-14-21](https://user-images.githubusercontent.com/65765090/204340030-27a195cb-d01b-4a7b-8ab5-689b0a99a0a9.jpg)

**Comment by YannVasseur35** [comment]
You can modify the jsQR.js code in a fork of this project or make your own lib based on this one.
