### ISSUE TITLE
does not prompt for video permisons

### ISSUE THREAD

**Issue by javirs85** [YannVasseur35/ReactorBlazorQRCodeScanner#6]
I created a blazor WASM (.NET7) run it in debug mode and visit the app url both from the laptop (with webcam) and a phone.  The app stays with the "Loading video stream (make sure you have a camera enabled)" message.

Nothing else happens.

**Comment by YannVasseur35** [comment]
Hi, did you allow the app for camera permissions ?

**Comment by javirs85** [comment]
did not get prompted

**Comment by javirs85** [comment]
I can open other websites that demo QR reading via JS and it opens the video stream. Not in my blazor project.

**Comment by javirs85** [comment]
If you mean setting something up in the Blazor project, no. I wasn't aware and changed no configuration. 
Where can I find this ?

**Comment by javirs85** [comment]
I created a .Net6 project and not it does work from google chrome on Windows. It still does not prompt for permissions on chrome on android

**Comment by YannVasseur35** [comment]
check on your browser the "lock" icon 
![image](https://user-images.githubusercontent.com/105861047/226574440-75752a3a-2686-4c9b-9694-9b8d4f36fa3c.png)
that the cam is authorized 
![image](https://user-images.githubusercontent.com/105861047/226574523-60e71927-0dc7-4697-8eff-0c8674f77d6c.png)

**Comment by javirs85** [comment]
okay, I did not see such an icon but somehow removing all permisons in the phone and getting to it again worked. It asked for permision. Granted permission and it has video stream now.
The issue is that it does no read our QR (that are slightly larger than normal, with some extra alignment squares in between the QR itself)
But this issue can be closed, Thanks for your time !! 


There are other open issues about the big QR not being readable.

**Comment by YannVasseur35** [comment]
The blazor lib relies on js lib to scan.  https://github.com/cozmo/jsQR

So if this one cannot scan your QR code, then the blazor one won't neither. 

You are not the first one to tell me that this lib does have issues of some sort of QR code. I personnaly have no issue with the one I use, but I made them.

**Comment by marcosgerene** [comment]
@javirs85 

I have the same issue, it does work on my machine but when I publish it, it does not request camera permission...

PS: I am using docker.

Maybe it is because I am using http (not https)?
